# Generated by Django 2.2.6 on 2019-10-19 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('url_key', models.CharField(db_column='url-key', db_index=True, max_length=255)),
                ('meta_title', models.CharField(blank=True, db_column='meta-title', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, db_column='meta-description', null=True)),
                ('meta_keywords', models.TextField(blank=True, db_column='meta-keywords', null=True)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
