# Generated by Django 2.2.6 on 2019-10-24 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191020_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Loc'),
        ),
    ]
