# Generated by Django 2.2.6 on 2019-10-21 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191019_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Loc'),
        ),
    ]
