# Generated by Django 2.2.6 on 2019-11-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0002_auto_20191019_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesman',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
